tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "secondary-fixed-dim": "#6bd8cb",
                    "error-container": "#ffdad6",
                    "background": "#f8f9ff",
                    "on-tertiary": "#ffffff",
                    "surface-bright": "#f8f9ff",
                    "surface-container-high": "#dce9ff",
                    "inverse-surface": "#213145",
                    "outline-variant": "#c6c6cd",
                    "on-error": "#ffffff",
                    "primary-container": "#131b2e",
                    "secondary-fixed": "#89f5e7",
                    "surface": "#f8f9ff",
                    "primary": "#000000",
                    "inverse-primary": "#bec6e0",
                    "surface-dim": "#cbdbf5",
                    "on-tertiary-fixed": "#341100",
                    "on-surface-variant": "#45464d",
                    "inverse-on-surface": "#eaf1ff",
                    "tertiary-fixed-dim": "#ffb690",
                    "tertiary-container": "#341100",
                    "surface-container-lowest": "#ffffff",
                    "outline": "#76777d",
                    "on-secondary-fixed": "#00201d",
                    "on-primary-container": "#7c839b",
                    "on-error-container": "#93000a",
                    "on-primary-fixed": "#131b2e",
                    "on-secondary": "#ffffff",
                    "on-secondary-container": "#006f66",
                    "surface-container": "#e5eeff",
                    "on-primary": "#ffffff",
                    "tertiary-fixed": "#ffdbca",
                    "surface-variant": "#d3e4fe",
                    "surface-container-low": "#eff4ff",
                    "on-tertiary-fixed-variant": "#783200",
                    "primary-fixed-dim": "#bec6e0",
                    "tertiary": "#000000",
                    "secondary": "#006a61",
                    "primary-fixed": "#dae2fd",
                    "on-tertiary-container": "#d95f00",
                    "error": "#ba1a1a",
                    "surface-tint": "#565e74",
                    "on-surface": "#0b1c30",
                    "secondary-container": "#86f2e4",
                    "on-primary-fixed-variant": "#3f465c",
                    "on-background": "#0b1c30",
                    "surface-container-highest": "#d3e4fe",
                    "on-secondary-fixed-variant": "#005049"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "unit": "8px",
                    "margin-mobile": "20px",
                    "container-max": "1280px",
                    "margin-desktop": "64px",
                    "section-gap": "80px",
                    "gutter": "24px"
            },
            "fontFamily": {
                    "label-lg": ["Inter"],
                    "headline-lg-mobile": ["Montserrat"],
                    "label-sm": ["Inter"],
                    "body-lg": ["Inter"],
                    "display": ["Montserrat"],
                    "body-md": ["Inter"],
                    "headline-md": ["Montserrat"],
                    "headline-lg": ["Montserrat"]
            },
            "fontSize": {
                    "label-lg": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600"}],
                    "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "600"}],
                    "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                    "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}]
            }
          },
        },
      }